### ISSUE TITLE
cdn资源过期

### ISSUE THREAD

**Issue by baseSky** [suframe/think-admin#3]
【重要通知】：
BootCDN 对外提供服务的域名已经于两年前（即 2020 年）变更为新域名 cdn.bootcdn.net，
老域名 cdn.bootcss.com 将于 2022 年 3 月 31 日下线。
请尽快切换到新域名，以免影响贵站功能！！！

**Comment by baseSky** [comment]
![image](https://user-images.githubusercontent.com/22609772/153548985-39d8c891-a3a0-4e4c-9763-8ceb28a570c3.png)

**Comment by baseSky** [comment]
https://cdn.bootcdn.net/ajax/libs/layer/3.0.1/layer.min.js资源不存在，需要更换版本为3.1.1

**Comment by suframe** [comment]
已经更新了哈

**Comment by baseSky** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
